---
fixtures:
  symlinks:
    sudo: "#{source_dir}"
    common: "#{source_dir}/../common"
    concat: "#{source_dir}/../concat"
    rsync: "#{source_dir}/../rsync"
    stdlib: "#{source_dir}/../stdlib"
